---
- name: create user
  user:
    name: java_user
    shell: /bin/bash
    append: yes
    home: /home/java_user

- name: Create a 2048-bit SSH key for user java_user in ~java_user/.ssh/id_rsa
  user:
    name: java_user
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

 # user name
#- sudo
#- ssh keys