---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Creating ssh directory
  file:
    path: /home/java_user/.ssh
    state: directory
    owner: java_user
    group: wheel

- name: Uploading ssh keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: java_user
    group: wheel
    mode: 0400
  loop:
    - { src: "java_user", dest: "/home/java_user/.ssh" }
    - { src: "java_user.pub", dest: "/home/java_user/.ssh" }

- name: add SSH key with user java_user
  shell: |
    eval "$(ssh-agent)"
    ssh-add -k /home/java_user/.ssh/java_user
  become_user: java_user



