#-user name
#-sudo
#-ssh keys

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Create user java_user
  user:
    name: java_user
    group: wheel
    append: yes
    state: present

- name: Creating ssh directory
  file:
    path: /home/java_user/.ssh
    state: directory
    owner: java_user
    group: wheel
    mode: '0700'

- name: Uploading ssh keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: java_user
    group: wheel
    mode: 0400
  loop:
    - { src: "java_user", dest: "/home/java_user/.ssh" }
    - { src: "java_user.pub", dest: "/home/java_user/.ssh" }

- name: add SSH key with user java_user
  shell: |
    eval "$(ssh-agent)"
    ssh-add -k /home/java_user/.ssh/java_user
  become_user: java_user





#- name: Ansible copy
#    copy:
#      src: java_user.pub
#      dest: /home/java_user/.ssh
#
#- name: Ansible copy
#    copy:
#      src: java_user
#      dest: /home/java_user/.ssh