---
- name: create git project directory
  file:
    path: /home/java_user/HOMEWORK
    state: directory
    owner: java_user
    group: wheel
    mode: 0770

- name: Git checkout
  git:
    repo: git@github.com:liene-ma/HOMEWORK.git
    dest: "/home/java_user/HOMEWORK"
    accept_hostkey: yes
    key_file: /home/java_user/.ssh/java_user
  become: yes
  become_user: java_user

- name: Add java_home to environment
  lineinfile:
    path: /etc/environment
    line: JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk"

- name: compile java file
  shell: javac /home/java_user/HOMEWORK/src/com/company/DataStructuresTask2.java
  become_user: java_user

- name: Add classpath
  shell: export CLASSPATH=$CLASSPATH:/usr/lib/jvm/java-1.7.0-openjdk
  args:
    executable: /bin/bash

- name: Reload environment
  shell: source /etc/environment
  args:
    executable: /bin/bash

- name: run java file
  shell: java com.company.DataStructuresTask2
  register: out
  become_user: java_user
  args:
    chdir: /home/java_user/HOMEWORK/src/

- debug: var=out.stdout_lines

