---
- name: create directory GroupProject
  file:
    path: /home/java_user/GroupProject
    state: directory
    owner: java_user
    group: wheel
    mode: 0770

- name: Git checkout
  git:
    repo: git@github.com:liene-ma/GroupProject.git
    dest: "/home/java_user/GroupProject"
    version: master
    accept_hostkey: yes
    key_file: /home/java_user/.ssh/java_user
  remote_user: java_user



#
#- name: Download Java code from Git repository
#  git:
#    repo: ssh://git@github.com/mylogin/hello.git
#    dest: "/home/project_hello"
#    version: master
#    key_file: /home/java_user/.ssh/id_rsa
#    become: yes
#    become_user: java_user

#- name: Compile java program
#  shel: javac /home/project_hello/filename.java
#    become: yes
#    become_user: java_user
#
#- name: Run the java program
#  shel: java /home/project_hello/filename