---
- name: install git
  package:
    name: git
    state: present
    update_cache: yes

- name:  install java - devel
  package:
    name: java-1.7.0-openjdk-devel
    state: present
    update_cache: yes
