---
- name: install git
  package:
    name: git
    state: present
    update_cache: yes

- name: install OpenJDK 11JRE
  package:
    name: java-11-openjdk
    state: present
    update_cache: yes






